### ISSUE TITLE
get_status has 3 retries built-in

### ISSUE THREAD

**Issue by balloob** [Danielhiversen/pyMillLocal#6]
The `get_status` call has 3 retries built-in. It's the only call that has this. In Home Assistant, when the heaters are off and unreachable, 1 failed call should be enough to retry later. Now it will keep retrying each turned off heater 3 times.

Can we remove the retry and leave it up to the caller to decide how many times they want to try based on the error?

**Comment by Danielhiversen** [comment]
Agree, will look into improve this

**Comment by Danielhiversen** [comment]
Fixed by https://github.com/Danielhiversen/pyMillLocal/pull/7
